### ISSUE TITLE
[Question] May I know the purpose of having protocol Localizable

### ISSUE THREAD

**Issue by yccheok** [emenegro/xib-localization#1]
Hi @emenegro 

Thanks for the clearly written tutorial https://medium.com/@mario.negro.martin/easy-xib-and-storyboard-localization-b2794c69c9db and code example. It helps a lot for us to decide how our localization strategy should go.

There is a section in the code which doesn't look clear to me.

May I know, what is the purpose of having `protocol Localizable`? 

As, I do not see this Type being used in anywhere else in the code? I try to remove `protocol Localizable` from the code example, it is still working as it is.

Thank you very much.

**Comment by emenegro** [comment]
Hi @yccheok,

Thank you so much for your kind words :)

About the `Localizable` protocol, is a way to mark a type as able to return a localized string, and by default is implemented by `String` which is usually the type used for keys. 

Of course you can get rid of it and just make:

```swift
extension String {
    public var localized: String {
        return NSLocalizedString(self, comment: "")
    }
}
```

But what I wanted is to give more semantics and being able to implement this protocol in any type, which allows you to abstract the behaviour in case you have to deal with several types returning localized versions of any of their properties.

That said, I agree it seems a bit superfluos in this simple scenario, and could be an addition just if the scenario with several types comes.

Regards.
